get rid of error: format not a string literal and no format arguments
Addressing:
+ gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -pie -o sign sign.c
sign.c: In function 'write_armored_signature':
sign.c:909:3: error: format not a string literal and no format arguments [-Werror=format-security]
   fprintf(fp, armor_signature_header);
   ^~~~~~~
sign.c:917:3: error: format not a string literal and no format arguments [-Werror=format-security]
   fprintf(fp, armor_signature_footer);
   ^~~~~~~

Signed-off-by: Miroslav Suchý <msuchy@redhat.com>